--CREACIÓN DE LA BASE DE DATOS GOLDENGYM

CREATE DATABASE GoldenGym;
GO

USE GoldenGym;
GO

CREATE TABLE Roles(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nombre NVARCHAR(80) NOT NULL,
);
CREATE TABLE Generos(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nombre NVARCHAR(40) NOT NULL
);
GO
go
CREATE TABLE Usurios(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdRol INT NOT NULL,
IdGenero INT NOT NULL,
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
[Login] NVARCHAR(50) NOT NULL,
[Password] NVARCHAR(100) NOT NULL,
FechaRegistro DATETIME NOT NULL,
Estatus TINYINT NOT NULL,
FOREIGN KEY (IdRol) REFERENCES Roles(Id),
FOREIGN KEY (IdGenero) REFERENCES Generos(Id)
);
go

CREATE TABLE Clientes(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdGenero INT NOT NULL,
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
Codigo NVARCHAR (20) NOT NULL,
Email NVARCHAR (100) NULL,
Telefono NVARCHAR(20) NULL,
Edad INT NULL,
FechaRegistro DATETIME NOT NULL,
Estatus TINYINT NOT NULL,
FOREIGN KEY(IdGenero) REFERENCES Generos(Id)
);
go

CREATE TABLE TipoMembresias(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nombre NVARCHAR (100) NOT NULL,
Descripcion NVARCHAR(MAX) NOT NULL,
Precio MONEY NOT NULL,
Duracion INT NOT NULL,
Estatus TINYINT 
);

CREATE TABLE Membresias(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCliente INT NOT NULL,
IdTipoMembresia INT NOT NULL,
FechaRegistro DATETIME NOT NULL,
FechaVencimiento DATETIME NOT NULL,
Estatus TINYINT NOT NULL,
FOREIGN KEY(IdCliente)REFERENCES Clientes(Id),
FOREIGN KEY(IdTipoMembresia)REFERENCES TipoMembresias(Id)
);